project:
  type: website
  resources: 
    - "*.pdf"

website:
  title: "Web materiales Analisis de Datos"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: sesion0.qmd
        text: "Overview curso"
      - href: talleres.qmd
        text: "talleres"
      - text: "Sesiones"
        menu:
          - sesion1.qmd
          - sesion2.qmd
          - sesion3.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

